version: '3.9'

services:
  reverse-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "4444:80"
    volumes:
      - mangrove:/data/nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx

  mangrove-db:
    container_name: mangrove-db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mangrove:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    env_file:
      - .env

  mangrove:
    container_name: mangrove
    build: .
    depends_on:
      - mangrove-db
      - reverse-proxy
    volumes:
      - mangrove:/app
      - /app/node_modules
    env_file:
      - .env
    entrypoint: node build/main.js

volumes:
  mangrove:


secrets:
  MONGO_USER:
    file: MONGO_USER
  MONGO_PASS:
    file: MONGO_PASS
